import { ReactNode } from 'react';
import { AppMailProps, AppMailReplyProps, AppMailSidebarItem, CustomEvent, LayoutType, SortOrderType } from './demo';
import { ToastType, ToastProps, ToastRef, PaginatorProps } from './components';
import { ElementCodeEditorData,ECodeEditorPreviewProps, ElementCodeEditorHeaderProps, ESaveData, ESaveFormData, ESaveModalProps } from './elements';
import { WebConfigCardProps, WebConfigCardItems, WebConfigEditModalProps } from './webconfig';
import {
    AppBreadcrumbProps,
    AppConfigProps,
    AppMenuItem,
    AppMenuItemProps,
    AppTopbarRef,
    Breadcrumb,
    BreadcrumbItem,
    ChatContextProps,
    ClassArray,
    ClassDictionary,
    ClassValue,
    ColorTheme,
    CSSTransitionProps,
    DashboardData,
    LayoutConfig,
    LayoutContextProps,
    LayoutState,
    MailContextProps,
    MenuContextProps,
    MenuModel,
    MenuProps,
    NodeRef,
    Page,
    TaskContextProps,
    TreeNode,
    TreeSelectionKeysType,
    TreeTableSelectionKeysType,
} from './layout';

type ChildContainerProps = {
    children: ReactNode;
};

export type {
    AppBreadcrumbProps,
    AppConfigProps,
    AppMailProps,
    AppMailReplyProps,
    AppMailSidebarItem,
    AppMenuItem,
    AppMenuItemProps,
    AppTopbarRef,
    Breadcrumb,
    Breadcrumb,
    BreadcrumbItem,
    ChildContainerProps,
    ColorTheme,
    CSSTransitionProps,
    CustomEvent,
    LayoutConfig,
    LayoutContextProps,
    LayoutState,
    MenuContextProps,
    MenuModel,
    MenuProps,
    NodeRef,
    PaginatorProps,
    WebConfigCardProps,
    WebConfigCardItems,
    WebConfigEditModalProps,
    ToastType,
    ToastProps,
    ToastRef,
    ElementCodeEditorData,
    ECodeEditorPreviewProps,
    ElementCodeEditorHeaderProps,
    ESaveData,
    ESaveFormData,
    ESaveModalProps,
};
