export interface ProjectFileItem {
    id: string;
    name: string;
    type: 'file' | 'folder';
    content?: string;
    extension?: string;
    children?: ProjectFileItem[];
    parentId?: string;
    saved?: boolean;
}

export const DEFAULT_NEXT_JS_FILES: ProjectFileItem[] = [
    {
        id: 'app',
        name: 'app',
        type: 'folder',
        children: [
            {
                id: 'globals-css',
                name: 'globals.css',
                type: 'file',
                extension: 'css',
                content:
                    '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --foreground-rgb: 0, 0, 0;\n  --background-start-rgb: 214, 219, 220;\n  --background-end-rgb: 255, 255, 255;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --foreground-rgb: 255, 255, 255;\n    --background-start-rgb: 0, 0, 0;\n    --background-end-rgb: 0, 0, 0;\n  }\n}\n\nbody {\n  color: rgb(var(--foreground-rgb));\n  background: linear-gradient(\n      to bottom,\n      transparent,\n      rgb(var(--background-end-rgb))\n    )\n    rgb(var(--background-start-rgb));\n}',
                parentId: 'app',
                saved: true,
            },
            {
                id: 'layout-tsx',
                name: 'layout.tsx',
                type: 'file',
                extension: 'tsx',
                content:
                    'import type { Metadata } from "next";\nimport { Inter } from "next/font/google";\nimport "./globals.css";\n\nconst inter = Inter({ subsets: ["latin"] });\n\nexport const metadata: Metadata = {\n  title: "Create Next App",\n  description: "Generated by create next app",\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang="en">\n      <body className={inter.className}>{children}</body>\n    </html>\n  );\n}',
                parentId: 'app',
                saved: true,
            },
            {
                id: 'page-tsx',
                name: 'page.tsx',
                type: 'file',
                extension: 'tsx',
                content:
                    'import Image from "next/image";\n\nexport default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-between p-24">\n      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">\n        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">\n          Get started by editing&nbsp;\n          <code className="font-mono font-bold">app/page.tsx</code>\n        </p>\n      </div>\n\n      <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:translate-y-1/4 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[\'\'] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[\'\'] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]">\n        <Image\n          className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"\n          src="/next.svg"\n          alt="Next.js Logo"\n          width={180}\n          height={37}\n          priority\n        />\n      </div>\n\n      <div className="mb-32 grid text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-4 lg:text-left">\n        <a\n          href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"\n          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"\n          target="_blank"\n          rel="noopener noreferrer"\n        >\n          <h2 className={`mb-3 text-2xl font-semibold`}>\n            Docs{" "}\n            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">\n              -&gt;\n            </span>\n          </h2>\n          <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>\n            Find in-depth information about Next.js features and API.\n          </p>\n        </a>\n\n        <a\n          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"\n          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"\n          target="_blank"\n          rel="noopener noreferrer"\n        >\n          <h2 className={`mb-3 text-2xl font-semibold`}>\n            Learn{" "}\n            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">\n              -&gt;\n            </span>\n          </h2>\n          <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>\n            Learn about Next.js in an interactive course with&nbsp;quizzes!\n          </p>\n        </a>\n\n        <a\n          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"\n          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"\n          target="_blank"\n          rel="noopener noreferrer"\n        >\n          <h2 className={`mb-3 text-2xl font-semibold`}>\n            Templates{" "}\n            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">\n              -&gt;\n            </span>\n          </h2>\n          <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>\n            Explore starter templates for Next.js.\n          </p>\n        </a>\n\n        <a\n          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"\n          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"\n          target="_blank"\n          rel="noopener noreferrer"\n        >\n          <h2 className={`mb-3 text-2xl font-semibold`}>\n            Deploy{" "}\n            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">\n              -&gt;\n            </span>\n          </h2>\n          <p className={`m-0 max-w-[30ch] text-sm opacity-50 text-balance`}>\n            Instantly deploy your Next.js site to a shareable URL with Vercel.\n          </p>\n        </a>\n      </div>\n    </main>\n  );\n}',
                parentId: 'app',
                saved: true,
            },
        ],
    },
    {
        id: 'components',
        name: 'components',
        type: 'folder',
        children: [],
        saved: true,
    },
    {
        id: 'lib',
        name: 'lib',
        type: 'folder',
        children: [
            {
                id: 'utils-ts',
                name: 'utils.ts',
                type: 'file',
                extension: 'ts',
                content:
                    'import { type ClassValue, clsx } from "clsx";\nimport { twMerge } from "tailwind-merge";\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}',
                parentId: 'lib',
                saved: true,
            },
        ],
        saved: true,
    },
    {
        id: 'public',
        name: 'public',
        type: 'folder',
        children: [
            {
                id: 'next-svg',
                name: 'next.svg',
                type: 'file',
                extension: 'svg',
                content:
                    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 394 80"><path fill="#000" d="M262 0h68.5v12.7h-27.2v66.6h-13.6V12.7H262V0ZM149 0v12.7H94v20.4h44.3v12.6H94v21h55v12.6H80.5V0h68.7zm34.3 0h-17.8l63.8 79.4h17.9l-32-39.7 32-39.7h-17.9l-23 28.6-23-28.6zm18.3 56.7-9-11-27.1 33.7h17.8l18.3-22.7z"/><path fill="#000" d="M81 79.3 17 0H0v79.3h13.6V17l50.2 62.3H81Zm252.6-.4c-1 0-1.8-.4-2.5-1s-1.1-1.6-1.1-2.6.3-1.8 1-2.5 1.6-1 2.6-1 1.8.3 2.5 1a3.4 3.4 0 0 1 .6 4.3 3.7 3.7 0 0 1-3 1.8zm23.2-33.5h6v23.3c0 2.1-.4 4-1.3 5.5a9.1 9.1 0 0 1-3.8 3.5c-1.6.8-3.5 1.3-5.7 1.3-2 0-3.7-.4-5.3-1s-2.8-1.8-3.7-3.2c-.9-1.3-1.4-3-1.4-5h6c.1.8.3 1.6.7 2.2s1 1.2 1.6 1.5c.7.4 1.5.5 2.4.5 1 0 1.8-.2 2.4-.6a4 4 0 0 0 1.6-1.8c.3-.8.5-1.8.5-3V45.5zm30.9 9.1a4.4 4.4 0 0 0-2-3.3 7.5 7.5 0 0 0-4.3-1.1c-1.3 0-2.4.2-3.3.5-.9.4-1.6 1-2 1.6a3.5 3.5 0 0 0-.3 4c.3.5.7.9 1.3 1.2l1.8 1 2 .5 3.2.8c1.3.3 2.5.7 3.7 1.2a13 13 0 0 1 3.2 1.8 8.1 8.1 0 0 1 3 6.5c0 2-.5 3.7-1.5 5.1a10 10 0 0 1-4.4 3.5c-1.8.8-4.1 1.2-6.8 1.2-2.6 0-4.9-.4-6.8-1.2-2-.8-3.4-2-4.5-3.5a10 10 0 0 1-1.7-5.6h6a5 5 0 0 0 3.5 4.6c1 .4 2.2.6 3.4.6 1.3 0 2.5-.2 3.5-.6 1-.4 1.8-1 2.4-1.7a4 4 0 0 0 .8-2.4c0-.9-.2-1.6-.7-2.2a11 11 0 0 0-2.1-1.4l-3.2-1-3.8-1c-2.8-.7-5-1.7-6.6-3.2a7.2 7.2 0 0 1-2.4-5.7 8 8 0 0 1 1.7-5 10 10 0 0 1 4.3-3.5c2-.8 4-1.2 6.4-1.2 2.3 0 4.4.4 6.2 1.2 1.8.8 3.2 2 4.2 3.4 1 1.4 1.5 3 1.5 5h-5.8z"/></svg>',
                parentId: 'public',
                saved: true,
            },
            {
                id: 'vercel-svg',
                name: 'vercel.svg',
                type: 'file',
                extension: 'svg',
                content:
                    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 283 64"><path fill="black" d="m141.04 16 c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.46 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM248.72 16c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.45 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM200.24 34c0 6 3.92 10 10 10 4.12 0 7.21-1.87 8.8-4.92l7.68 4.43c-3.18 5.3-9.14 8.49-16.48 8.49-11.05 0-19-7.2-19-18s7.96-18 19-18c7.34 0 13.29 3.19 16.48 8.49l-7.68 4.43c-1.59-3.05-4.68-4.92-8.8-4.92-6.07 0-10 4-10 10zm82.48-29v46h-9V5h9zM36.95 0L73.9 64H0L36.95 0zm92.38 5l-27.71 48L73.91 5H84.3l17.32 30 17.32-30h10.39zm58.91 12v9.69c-1-.29-2.06-.49-3.2-.49-5.81 0-10 4-10 10V51h-9V17h9v9.2c0-5.08 5.91-9.2 13.2-9.2z"/></svg>',
                parentId: 'public',
                saved: true,
            },
        ],
        saved: true,
    },
    {
        id: 'package-json',
        name: 'package.json',
        type: 'file',
        extension: 'json',
        content:
            '{\n  "name": "my-nextjs-project",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start",\n    "lint": "next lint"\n  },\n  "dependencies": {\n    "next": "14.0.4",\n    "react": "^18",\n    "react-dom": "^18",\n    "clsx": "^2.0.0",\n    "tailwind-merge": "^2.0.0"\n  },\n  "devDependencies": {\n    "typescript": "^5",\n    "@types/node": "^20",\n    "@types/react": "^18",\n    "@types/react-dom": "^18",\n    "autoprefixer": "^10.0.1",\n    "postcss": "^8",\n    "tailwindcss": "^3.3.0",\n    "eslint": "^8",\n    "eslint-config-next": "14.0.4"\n  }\n}',
        saved: true,
    },
    {
        id: 'tsconfig-json',
        name: 'tsconfig.json',
        type: 'file',
        extension: 'json',
        content:
            '{\n  "compilerOptions": {\n    "target": "es5",\n    "lib": ["dom", "dom.iterable", "esnext"],\n    "allowJs": true,\n    "skipLibCheck": true,\n    "strict": true,\n    "noEmit": true,\n    "esModuleInterop": true,\n    "module": "esnext",\n    "moduleResolution": "bundler",\n    "resolveJsonModule": true,\n    "isolatedModules": true,\n    "jsx": "preserve",\n    "incremental": true,\n    "plugins": [\n      {\n        "name": "next"\n      }\n    ],\n    "paths": {\n      "../../*": ["./*"]\n    }\n  },\n  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],\n  "exclude": ["node_modules"]\n}',
        saved: true,
    },
    {
        id: 'tailwind-config-ts',
        name: 'tailwind.config.ts',
        type: 'file',
        extension: 'ts',
        content:
            'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: [\n    "./pages/**/*.{js,ts,jsx,tsx,mdx}",\n    "./components/**/*.{js,ts,jsx,tsx,mdx}",\n    "./app/**/*.{js,ts,jsx,tsx,mdx}",\n  ],\n  theme: {\n    extend: {\n      backgroundImage: {\n        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",\n        "gradient-conic":\n          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",\n      },\n    },\n  },\n  plugins: [],\n};\nexport default config;',
        saved: true,
    },
    {
        id: 'postcss-config-js',
        name: 'postcss.config.js',
        type: 'file',
        extension: 'js',
        content: 'module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n}',
        saved: true,
    },
    {
        id: 'next-config-js',
        name: 'next.config.js',
        type: 'file',
        extension: 'js',
        content: "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\n\nmodule.exports = nextConfig",
        saved: true,
    },
    {
        id: 'eslintrc-json',
        name: '.eslintrc.json',
        type: 'file',
        extension: 'json',
        content: '{\n  "extends": "next/core-web-vitals"\n}',
        saved: true,
    },
    {
        id: 'gitignore',
        name: '.gitignore',
        type: 'file',
        extension: 'gitignore',
        content:
            '# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.\n\n# dependencies\n/node_modules\n/.pnp\n.pnp.js\n.yarn/install-state.gz\n\n# testing\n/coverage\n\n# next.js\n/.next/\n/out/\n\n# production\n/build\n\n# misc\n.DS_Store\n*.pem\n\n# debug\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# local env files\n.env*.local\n\n# vercel\n.vercel\n\n# typescript\n*.tsbuildinfo\nnext-env.d.ts',
        saved: true,
    },
    {
        id: 'readme-md',
        name: 'README.md',
        type: 'file',
        extension: 'md',
        content:
            'This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).\n\n## Getting Started\n\nFirst, run the development server:\n\n```bash\nnpm run dev\n# or\nyarn dev\n# or\npnpm dev\n# or\nbun dev\n```\n\nOpen [http://localhost:3000](http://localhost:3000) with your browser to see the result.\n\nYou can start editing the page by modifying `app/page.tsx`. The page auto-updates as you edit the file.\n\nThis project uses [`next/font`](https://nextjs.org/docs/basic-features/font-optimization) to automatically optimize and load Inter, a custom Google Font.\n\n## Learn More\n\nTo learn more about Next.js, take a look at the following resources:\n\n- [Next.js Documentation](https://nextjs.org/docs) - learn about Next.js features and API.\n- [Learn Next.js](https://nextjs.org/learn) - an interactive Next.js tutorial.\n\nYou can check out [the Next.js GitHub repository](https://github.com/vercel/next.js/) - your feedback and contributions are welcome!\n\n## Deploy on Vercel\n\nThe easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new?utm_medium=default-template&filter=next.js&utm_source=create-next-app&utm_campaign=create-next-app-readme) from the creators of Next.js.\n\nCheck out our [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.',
        saved: true,
    },
];

export const DEFAULT_VITE_FILES: ProjectFileItem[] = [
    {
        id: 'src',
        name: 'src',
        type: 'folder',
        children: [
            {
                id: 'app-tsx',
                name: 'App.tsx',
                type: 'file',
                extension: 'tsx',
                content:
                    'import { useState } from "react";\nimport reactLogo from "./assets/react.svg";\nimport viteLogo from "/vite.svg";\nimport "./App.css";\n\nfunction App() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <>\n      <div>\n        <a href="https://vitejs.dev" target="_blank">\n          <img src={viteLogo} className="logo" alt="Vite logo" />\n        </a>\n        <a href="https://react.dev" target="_blank">\n          <img src={reactLogo} className="logo react" alt="React logo" />\n        </a>\n      </div>\n      <h1>Vite + React</h1>\n      <div className="card">\n        <button onClick={() => setCount((count) => count + 1)}>\n          count is {count}\n        </button>\n        <p>\n          Edit <code>src/App.tsx</code> and save to test HMR\n        </p>\n      </div>\n      <p className="read-the-docs">\n        Click on the Vite and React logos to learn more\n      </p>\n    </>\n  );\n}\n\nexport default App;',
                parentId: 'src',
                saved: true,
            },
            {
                id: 'app-css',
                name: 'App.css',
                type: 'file',
                extension: 'css',
                content:
                    '#root {\n  max-width: 1280px;\n  margin: 0 auto;\n  padding: 2rem;\n  text-align: center;\n}\n\n.logo {\n  height: 6em;\n  padding: 1.5em;\n  will-change: filter;\n  transition: filter 300ms;\n}\n.logo:hover {\n  filter: drop-shadow(0 0 2em #646cffaa);\n}\n.logo.react:hover {\n  filter: drop-shadow(0 0 2em #61dafbaa);\n}\n\n@keyframes logo-spin {\n  from {\n    transform: rotate(0deg);\n  }\n  to {\n    transform: rotate(360deg);\n  }\n}\n\n@media (prefers-reduced-motion: no-preference) {\n  a:nth-of-type(2) .logo {\n    animation: logo-spin infinite 20s linear;\n  }\n}\n\n.card {\n  padding: 2em;\n}\n\n.read-the-docs {\n  color: #888;\n}',
                parentId: 'src',
                saved: true,
            },
            {
                id: 'index-css',
                name: 'index.css',
                type: 'file',
                extension: 'css',
                content:
                    '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --foreground-rgb: 0, 0, 0;\n  --background-start-rgb: 214, 219, 220;\n  --background-end-rgb: 255, 255, 255;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --foreground-rgb: 255, 255, 255;\n    --background-start-rgb: 0, 0, 0;\n    --background-end-rgb: 0, 0, 0;\n  }\n}\n\nbody {\n  color: rgb(var(--foreground-rgb));\n  background: linear-gradient(\n      to bottom,\n      transparent,\n      rgb(var(--background-end-rgb))\n    )\n    rgb(var(--background-start-rgb));\n}',
                parentId: 'src',
                saved: true,
            },
            {
                id: 'main-tsx',
                name: 'main.tsx',
                type: 'file',
                extension: 'tsx',
                content:
                    'import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App.tsx";\nimport "./index.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);',
                parentId: 'src',
                saved: true,
            },
            {
                id: 'vite-env-d-ts',
                name: 'vite-env.d.ts',
                type: 'file',
                extension: 'ts',
                content: '/// <reference types="vite/client" />',
                parentId: 'src',
                saved: true,
            },
            {
                id: 'assets',
                name: 'assets',
                type: 'folder',
                children: [
                    {
                        id: 'react-svg',
                        name: 'react.svg',
                        type: 'file',
                        extension: 'svg',
                        content:
                            '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--logos" width="35.93" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 228"><path fill="#00D8FF" d="M210.483 73.824a171.49 171.49 0 0 0-8.24-2.597c.465-1.9.893-3.777 1.273-5.621c6.238-30.281 2.16-54.676-11.769-62.708c-13.355-7.7-35.196.329-57.254 19.526a171.23 171.23 0 0 0-6.375 5.848a155.866 155.866 0 0 0-4.241-3.917C100.759 3.829 77.587-4.822 63.673 3.233C50.33 10.957 46.379 33.89 51.995 62.588a170.974 170.974 0 0 0 1.892 8.48c-3.28.932-6.445 1.924-9.474 2.98C17.309 83.498 0 98.307 0 113.668c0 15.865 18.582 31.778 46.812 41.427a145.52 145.52 0 0 0 6.921 2.165a167.467 167.467 0 0 0-2.01 9.138c-5.354 28.2-1.173 50.591 12.134 58.266c13.744 7.926 36.812-.22 59.273-19.855a145.567 145.567 0 0 0 5.342-4.923a168.064 168.064 0 0 0 6.92 6.314c21.758 18.722 43.246 26.282 56.54 18.586c13.731-7.949 18.194-32.003 12.4-61.268a145.016 145.016 0 0 0-1.535-6.842c1.62-.48 3.21-.974 4.76-1.488c29.348-9.723 48.443-25.443 48.443-41.52c0-15.417-17.868-30.326-45.517-39.844Zm-6.365 70.984c-1.4.463-2.836.91-4.3 1.345c-3.24-10.257-7.612-21.163-12.963-32.432c5.106-11 9.31-21.767 12.459-31.957c2.619.758 5.16 1.557 7.61 2.4c23.69 8.156 38.14 20.213 38.14 29.504c0 9.896-15.606 22.743-40.946 31.14Zm-10.514 20.834c2.562 12.94 2.927 24.64 1.23 33.787c-1.524 8.219-4.59 13.698-8.382 15.893c-8.067 4.67-25.32-1.4-43.927-17.412a156.726 156.726 0 0 1-6.437-5.87c7.214-7.889 14.423-17.06 21.459-27.246c12.376-1.098 24.068-2.894 34.671-5.345a134.17 134.17 0 0 1 1.386 6.193ZM87.276 214.515c-7.882 2.783-14.16 2.863-17.955.675c-8.075-4.657-11.432-22.636-6.853-46.752a156.923 156.923 0 0 1 1.869-8.499c10.486 2.32 22.093 3.988 34.498 4.994c7.084 9.967 14.501 19.128 21.976 27.15a134.668 134.668 0 0 1-4.877 4.492c-9.933 8.682-19.886 14.842-28.658 17.94ZM50.35 144.747c-12.483-4.267-22.792-9.812-29.858-15.863c-6.35-5.437-9.555-10.836-9.555-15.216c0-9.322 13.897-21.212 37.076-29.293c2.813-.98 5.757-1.905 8.812-2.773c3.204 10.42 7.406 21.315 12.477 32.332c-5.137 11.18-9.399 22.249-12.634 32.792a134.718 134.718 0 0 1-6.318-1.979Zm12.378-84.26c-4.811-24.587-1.616-43.134 6.425-47.789c8.564-4.958 27.502 2.111 47.463 19.835a144.318 144.318 0 0 1 3.841 3.545c-7.438 7.987-14.787 17.08-21.808 26.988c-12.04 1.116-23.565 2.908-34.161 5.309a160.342 160.342 0 0 1-1.76-7.887Zm110.427 27.268a347.8 347.8 0 0 0-7.785-12.803c8.168 1.033 15.994 2.404 23.343 4.08c-2.206 7.072-4.956 14.465-8.193 22.045a381.151 381.151 0 0 0-7.365-13.322Zm-45.032-43.861c5.044 5.465 10.096 11.566 15.065 18.186a322.04 322.04 0 0 0-30.257-.006c4.974-6.559 10.069-12.652 15.192-18.18ZM82.802 87.83a323.167 323.167 0 0 0-7.227 13.238c-3.184-7.553-5.909-14.98-8.134-22.152c7.304-1.634 15.093-2.97 23.209-3.984a321.524 321.524 0 0 0-7.848 12.897Zm8.081 65.352c-8.385-.936-16.291-2.203-23.593-3.793c2.26-7.3 5.045-14.885 8.298-22.6a321.187 321.187 0 0 0 7.257 13.246c2.594 4.48 5.28 8.868 8.038 13.147Zm37.542 31.03c-5.184-5.592-10.354-11.779-15.403-18.433c4.902.192 9.899.29 14.978.29c5.218 0 10.376-.117 15.453-.343c-4.985 6.774-10.018 12.97-15.028 18.486Zm52.198-57.817c3.422 7.8 6.306 15.345 8.596 22.52c-7.422 1.694-15.436 3.058-23.88 4.071a382.417 382.417 0 0 0 7.859-13.026a347.403 347.403 0 0 0 7.425-13.565Zm-16.898 8.101a358.557 358.557 0 0 1-12.281 19.815a329.4 329.4 0 0 1-23.444.823c-7.967 0-15.716-.248-23.178-.732a310.202 310.202 0 0 1-12.513-19.846h.001a307.41 307.41 0 0 1-10.923-20.627a310.278 310.278 0 0 1 10.89-20.637l-.001.001a307.318 307.318 0 0 1 12.413-19.761c7.613-.576 15.42-.876 23.31-.876H128c7.926 0 15.743.303 23.354.883a329.357 329.357 0 0 1 12.335 19.695a358.489 358.489 0 0 1 11.036 20.54a329.472 329.472 0 0 1-11 20.722Zm22.56-122.124c8.572 4.944 11.906 24.881 6.52 51.026c-.344 1.668-.73 3.367-1.15 5.09c-10.622-2.452-22.155-4.275-34.23-5.408c-7.034-10.017-14.323-19.124-21.64-27.008a160.789 160.789 0 0 1 5.888-5.4c18.9-16.447 36.564-22.941 44.612-18.3ZM128 90.808c12.625 0 22.86 10.235 22.86 22.86s-10.235 22.86-22.86 22.86s-22.86-10.235-22.86-22.86s10.235-22.86 22.86-22.86Z"></path></svg>',
                        parentId: 'assets',
                        saved: true,
                    },
                ],
                parentId: 'src',
                saved: true,
            },
            {
                id: 'components',
                name: 'components',
                type: 'folder',
                children: [],
                parentId: 'src',
                saved: true,
            },
            {
                id: 'lib',
                name: 'lib',
                type: 'folder',
                children: [
                    {
                        id: 'utils-ts',
                        name: 'utils.ts',
                        type: 'file',
                        extension: 'ts',
                        content:
                            'import { type ClassValue, clsx } from "clsx";\nimport { twMerge } from "tailwind-merge";\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}',
                        parentId: 'lib',
                        saved: true,
                    },
                ],
                parentId: 'src',
                saved: true,
            },
        ],
        saved: true,
    },
    {
        id: 'public',
        name: 'public',
        type: 'folder',
        children: [
            {
                id: 'vite-svg',
                name: 'vite.svg',
                type: 'file',
                extension: 'svg',
                content:
                    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--logos" width="31.88" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 257"><defs><linearGradient id="IconifyId1813088fe1fbc01fb466" x1="-.828%" x2="57.636%" y1="7.652%" y2="78.411%"><stop offset="0%" stop-color="#41D1FF"></stop><stop offset="100%" stop-color="#BD34FE"></stop></linearGradient><linearGradient id="IconifyId1813088fe1fbc01fb467" x1="43.376%" x2="50.316%" y1="2.242%" y2="89.03%"><stop offset="0%" stop-color="#FFEA83"></stop><stop offset="8.333%" stop-color="#FFDD35"></stop><stop offset="100%" stop-color="#FFA800"></stop></linearGradient></defs><path fill="url(#IconifyId1813088fe1fbc01fb466)" d="M255.153 37.938L134.897 252.976c-2.483 4.44-8.862 4.466-11.382.048L.875 37.958c-2.746-4.814 1.371-10.646 6.827-9.67l120.385 21.517a6.537 6.537 0 0 0 2.322-.004l117.867-21.483c5.438-.991 9.574 4.796 6.877 9.62Z"></path><path fill="url(#IconifyId1813088fe1fbc01fb467)" d="M185.432.063L96.44 17.501a3.268 3.268 0 0 0-2.634 3.014l-5.474 92.456a3.268 3.268 0 0 0 3.997 3.378l24.777-5.718c2.318-.535 4.413 1.507 3.936 3.838l-7.361 36.047c-.495 2.426 1.782 4.5 4.151 3.78l15.304-4.649c2.372-.72 4.652 1.36 4.15 3.788l-11.698 56.621c-.732 3.542 3.979 5.473 5.943 2.437l1.313-2.028l72.516-144.72c1.215-2.423-.88-5.186-3.54-4.672l-25.505 4.922c-2.396.462-4.435-1.77-3.759-4.114l16.646-57.705c.677-2.35-1.37-4.583-3.769-4.113Z"></path></svg>',
                parentId: 'public',
                saved: true,
            },
        ],
        saved: true,
    },
    {
        id: 'package-json',
        name: 'package.json',
        type: 'file',
        extension: 'json',
        content:
            '{\n  "name": "my-vite-react-project",\n  "private": true,\n  "version": "0.0.0",\n  "type": "module",\n  "scripts": {\n    "dev": "vite",\n    "build": "tsc && vite build",\n    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",\n    "preview": "vite preview"\n  },\n  "dependencies": {\n    "react": "^18.2.0",\n    "react-dom": "^18.2.0",\n    "clsx": "^2.0.0",\n    "tailwind-merge": "^2.0.0"\n  },\n  "devDependencies": {\n    "@types/react": "^18.2.66",\n    "@types/react-dom": "^18.2.22",\n    "@typescript-eslint/eslint-plugin": "^7.2.0",\n    "@typescript-eslint/parser": "^7.2.0",\n    "@vitejs/plugin-react": "^4.2.1",\n    "autoprefixer": "^10.4.19",\n    "eslint": "^8.57.0",\n    "eslint-plugin-react-hooks": "^4.6.0",\n    "eslint-plugin-react-refresh": "^0.4.6",\n    "postcss": "^8.4.38",\n    "tailwindcss": "^3.4.4",\n    "typescript": "^5.2.2",\n    "vite": "^5.2.0"\n  }\n}',
        saved: true,
    },
    {
        id: 'tsconfig-json',
        name: 'tsconfig.json',
        type: 'file',
        extension: 'json',
        content:
            '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "useDefineForClassFields": true,\n    "lib": ["ES2020", "DOM", "DOM.Iterable"],\n    "module": "ESNext",\n    "skipLibCheck": true,\n\n    /* Bundler mode */\n    "moduleResolution": "bundler",\n    "allowImportingTsExtensions": true,\n    "resolveJsonModule": true,\n    "isolatedModules": true,\n    "noEmit": true,\n    "jsx": "react-jsx",\n\n    /* Linting */\n    "strict": true,\n    "noUnusedLocals": true,\n    "noUnusedParameters": true,\n    "noFallthroughCasesInSwitch": true,\n\n    /* Path mapping */\n    "baseUrl": ".",\n    "paths": {\n      "../../*": ["./src/*"]\n    }\n  },\n  "include": ["src"],\n  "references": [{ "path": "./tsconfig.node.json" }]\n}',
        saved: true,
    },
    {
        id: 'tsconfig-node-json',
        name: 'tsconfig.node.json',
        type: 'file',
        extension: 'json',
        content:
            '{\n  "compilerOptions": {\n    "composite": true,\n    "skipLibCheck": true,\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "allowSyntheticDefaultImports": true,\n    "strict": true\n  },\n  "include": ["vite.config.ts"]\n}',
        saved: true,
    },
    {
        id: 'vite-config-ts',
        name: 'vite.config.ts',
        type: 'file',
        extension: 'ts',
        content:
            'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\nimport path from "path";\n\n// https://vitejs.dev/config/\nexport default defineConfig({\n  plugins: [react()],\n  resolve: {\n    alias: {\n      "@": path.resolve(__dirname, "./src"),\n    },\n  },\n});',
        saved: true,
    },
    {
        id: 'tailwind-config-js',
        name: 'tailwind.config.js',
        type: 'file',
        extension: 'js',
        content:
            '/** @type {import("tailwindcss").Config} */\nexport default {\n  content: [\n    "./index.html",\n    "./src/**/*.{js,ts,jsx,tsx}",\n  ],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n}',
        saved: true,
    },
    {
        id: 'postcss-config-js',
        name: 'postcss.config.js',
        type: 'file',
        extension: 'js',
        content: 'export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n}',
        saved: true,
    },
    {
        id: 'eslintrc-cjs',
        name: '.eslintrc.cjs',
        type: 'file',
        extension: 'cjs',
        content:
            'module.exports = {\n  root: true,\n  env: { browser: true, es2020: true },\n  extends: [\n    "eslint:recommended",\n    "@typescript-eslint/recommended",\n    "eslint-plugin-react-hooks/recommended",\n  ],\n  ignorePatterns: ["dist", ".eslintrc.cjs"],\n  parser: "@typescript-eslint/parser",\n  plugins: ["react-refresh"],\n  rules: {\n    "react-refresh/only-export-components": [\n      "warn",\n      { allowConstantExport: true },\n    ],\n  },\n}',
        saved: true,
    },
    {
        id: 'gitignore',
        name: '.gitignore',
        type: 'file',
        extension: 'gitignore',
        content:
            '# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\npnpm-debug.log*\nlerna-debug.log*\n\nnode_modules\ndist\ndist-ssr\n*.local\n\n# Editor directories and files\n.vscode/*\n!.vscode/extensions.json\n.idea\n.DS_Store\n*.suo\n*.ntvs*\n*.njsproj\n*.sln\n*.sw?\n\n# Environment variables\n.env\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local',
        saved: true,
    },
    {
        id: 'index-html',
        name: 'index.html',
        type: 'file',
        extension: 'html',
        content:
            '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <link rel="icon" type="image/svg+xml" href="/vite.svg" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>Vite + React + TS</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>',
        saved: true,
    },
    {
        id: 'readme-md',
        name: 'README.md',
        type: 'file',
        extension: 'md',
        content:
            '# React + TypeScript + Vite\n\nThis template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.\n\nCurrently, two official plugins are available:\n\n- [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md) uses [Babel](https://babeljs.io/) for Fast Refresh\n- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh\n\n## Expanding the ESLint configuration\n\nIf you are developing a production application, we recommend updating the configuration to enable type aware lint rules:\n\n- Configure the top-level `parserOptions` property like this:\n\n```js\nexport default {\n  // other rules...\n  parserOptions: {\n    ecmaVersion: "latest",\n    sourceType: "module",\n    project: ["./tsconfig.json", "./tsconfig.node.json"],\n    tsconfigRootDir: __dirname,\n  },\n}\n```\n\n- Replace `plugin:@typescript-eslint/recommended` to `plugin:@typescript-eslint/recommended-type-checked` or `plugin:@typescript-eslint/strict-type-checked`\n- Optionally add `plugin:@typescript-eslint/stylistic-type-checked`\n- Install [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react) and add `plugin:react/recommended` & `plugin:react/jsx-runtime` to the `extends` list\n\n## Getting Started\n\nFirst, install the dependencies:\n\n```bash\nnpm install\n# or\nyarn install\n# or\npnpm install\n# or\nbun install\n```\n\nThen, run the development server:\n\n```bash\nnpm run dev\n# or\nyarn dev\n# or\npnpm dev\n# or\nbun dev\n```\n\nOpen [http://localhost:5173](http://localhost:5173) with your browser to see the result.\n\nYou can start editing the page by modifying `src/App.tsx`. The page auto-updates as you edit the file.\n\n## Building for Production\n\nTo build the app for production:\n\n```bash\nnpm run build\n# or\nyarn build\n# or\npnpm build\n# or\nbun build\n```\n\nTo preview the production build:\n\n```bash\nnpm run preview\n# or\nyarn preview\n# or\npnpm preview\n# or\nbun preview\n```',
        saved: true,
    },
];

export const DEFAULT_ASTRO_FILES: ProjectFileItem[] = [
    {
        id: 'public',
        name: 'public',
        type: 'folder',
        children: [
            {
                id: 'favicon-svg',
                name: 'favicon.svg',
                type: 'file',
                extension: 'svg',
                content: `<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="32" height="32" rx="8" fill="#007bff"/>
  <path d="M8 8h16v16H8z" fill="white" opacity="0.9"/>
</svg>`,
                parentId: 'public',
                saved: true,
            },
        ],
        saved: true,
    },
    {
        id: 'src',
        name: 'src',
        type: 'folder',
        children: [
            {
                id: 'components',
                name: 'components',
                type: 'folder',
                children: [],
                parentId: 'src',
                saved: true,
            },
            {
                id: 'layouts',
                name: 'layouts',
                type: 'folder',
                children: [
                    {
                        id: 'layout-astro',
                        name: 'Layout.astro',
                        type: 'file',
                        extension: 'astro',
                        content: `---
import "../styles/global.css";

export interface Props {
  title?: string;
  description?: string;
}

const { 
  title = "My Website",
  description = ""
} = Astro.props;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <meta name="description" content={description} />
    <meta property="og:title" content={title} />
    <meta property="og:description" content={description} />
    <meta property="og:site_name" content="My Website" />
    <title>{title}</title>
  </head>
  <body class="seamless">
    <slot />
  </body>
</html>

<style>
  html,
  body {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
  }
</style>
`,
                        parentId: 'layouts',
                        saved: true,
                    },
                ],
                parentId: 'src',
                saved: true,
            },
            {
                id: 'pages',
                name: 'pages',
                type: 'folder',
                children: [
                    {
                        id: '404-astro',
                        name: '404.astro',
                        type: 'file',
                        extension: 'astro',
                        content: `---
import Layout from '../layouts/Layout.astro';
---

<Layout title="Page Not Found - My Website">
  <main class="min-h-screen w-full flex items-center justify-center px-4">
    <div class="text-center">
      <h1 class="text-6xl font-bold text-gray-900 mb-4">404</h1>
      <h2 class="text-2xl font-semibold text-gray-700 mb-6">Page Not Found</h2>
      <p class="text-gray-600 mb-8">The page you're looking for doesn't exist.</p>
      <a 
        href="/" 
        class="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
      >
        Go Home
      </a>
    </div>
  </main>
</Layout>`,
                        parentId: 'pages',
                        saved: true,
                    },
                    {
                        id: 'index-astro',
                        name: 'index.astro',
                        type: 'file',
                        extension: 'astro',
                        content: `---
import Layout from "../layouts/Layout.astro";
// Page metadata
const title = "My Website";
const description = "";
---

<Layout title={title} description={description}>
  <main class="w-full min-h-screen seamless">
    <!-- Seamless Component Layout - No Gaps, Full Width -->
    <div class="component-container seamless">hai</div>
  </main>
</Layout>

<style>
  /* Component-specific styles */
  .component-container {
    display: flex;
    flex-direction: column;
    width: 100%;
    margin: 0;
    padding: 0;
    gap: 0;
  }

  .component-container > * {
    width: 100%;
    max-width: 100%;
    flex-shrink: 0;
  }

  /* Smooth animations */
  .fade-in {
    opacity: 0;
    animation: fadeIn 0.6s ease-out forwards;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  /* Ensure seamless connection between components */
  @media (min-width: 768px) {
    .component-container {
      min-height: 100vh;
    }
  }
</style>`,
                        parentId: 'pages',
                        saved: true,
                    },
                ],
                parentId: 'src',
                saved: true,
            },
            {
                id: 'styles',
                name: 'styles',
                type: 'folder',
                children: [
                    {
                        id: 'global-css',
                        name: 'global.css',
                        type: 'file',
                        extension: 'css',
                        content: `@import "tailwindcss";

/* Global styles for seamless components */
html, body {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  scroll-behavior: smooth;
  color:white;
  background-color: #121212;
}

* {
  box-sizing: border-box;
}

.seamless {
  margin: 0;
  padding: 0;
  width: 100%;
}
`,
                        parentId: 'styles',
                        saved: true,
                    },
                ],
                parentId: 'src',
                saved: true,
            },
        ],
        saved: true,
    },

    {
        id: 'env',
        name: '.env.example',
        type: 'file',
        extension: 'example',
        content: `# Environment variables for My Website
PUBLIC_SITE_NAME="My Website"
PUBLIC_SITE_DESCRIPTION=""
PUBLIC_SITE_URL="https://your-site.com"

# Add your environment variables here
# API_KEY=
# DATABASE_URL=
# PRIVATE_KEY=`,
        saved: true,
    },
    {
        id: 'eslintrc-cjs',
        name: '.eslintrc.cjs',
        type: 'file',
        extension: 'cjs',
        content: `/** @type {import('eslint').Linter.Config} */
module.exports = {
  extends: [
    'eslint:recommended',
    '@typescript-eslint/recommended',
    'plugin:astro/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/no-explicit-any': 'warn',
    'astro/no-conflict-set-directives': 'error',
    'astro/no-unused-define-vars-in-style': 'error',
  },
  overrides: [
    {
      files: ['*.astro'],
      parser: 'astro-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.astro'],
      },
    },
  ],
};
`,
        saved: true,
    },

    {
        id: 'gitignore',
        name: '.gitignore',
        type: 'file',
        extension: 'gitignore',
        content: `# build output
dist/

# generated types
.astro/

# dependencies
node_modules/

# logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# environment variables
.env
.env.production

# macOS-specific files
.DS_Store

# jetbrains setting folder
.idea/
`,
        saved: true,
    },

    {
        id: 'astro-config-mjs',
        name: 'astro.config.mjs',
        type: 'file',
        extension: 'mjs',
        content: `// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [tailwindcss()]
  }
});
`,
        saved: true,
    },

    {
        id: 'package-json',
        name: 'package.json',
        type: 'file',
        extension: 'json',
        content: `{
  "name": "my-website",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@tailwindcss/vite": "^4.1.8",
    "astro": "^5.8.0",
    "tailwindcss": "^4.1.8"
  }
}`,
        saved: true,
    },
    {
        id: 'tsconfig-json',
        name: 'tsconfig.json',
        type: 'file',
        extension: 'json',
        content: `{
  "extends": "astro/tsconfigs/strict",
  "include": [
    ".astro/types.d.ts",
    "**/*"
  ],
  "exclude": [
    "dist"
  ]
}`,
        saved: true,
    },

    {
        id: 'readme-md',
        name: 'README.md',
        type: 'file',
        extension: 'md',
        content: `# Modern Astro Starter with Tailwind CSS

A modern, performant Astro starter template with Tailwind CSS integration and TypeScript support.

## ✨ Features

- 🚀 **Astro 4** - The latest version of Astro
- 🎨 **Tailwind CSS** - Utility-first CSS framework
- 📝 **TypeScript** - Type-safe development
- 🎯 **Modern Components** - Clean, reusable Astro components
- 📱 **Responsive Design** - Mobile-first approach
- 🌙 **Dark Theme** - Beautiful dark color scheme
- ⚡ **Optimized Performance** - Fast loading and great Core Web Vitals

## 🚀 Quick Start

\`\`\`sh
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build

# Preview production build
npm run preview
\`\`\`

`,
        saved: true,
    },
];

export const DEFAULT_HTML_FILES: ProjectFileItem[] = [
    {
        id: 'index-html',
        name: 'index.html',
        type: 'file',
        extension: 'html',
        content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <script src="https://unpkg.com/tailwindcss-cdn@3.4.0/tailwindcss.js"></script>
</head>
<body class="bg-gray-50 min-h-screen flex items-center justify-center">
    <div class="text-center">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">Welcome</h1>
        <p class="text-lg text-gray-600">Your new HTML project is ready!</p>
    </div>
</body>
</html>`,
        saved: true,
    },
    {
        id: 'styles-css',
        name: 'styles.css',
        type: 'file',
        extension: 'css',
        content: `/* Global styles for seamless components */
html, body {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  scroll-behavior: smooth;
  color:white;
  background-color: #121212;
}

* {
  box-sizing: border-box;
}

.seamless {
  margin: 0;
  padding: 0;
  width: 100%;
}`,
        saved: true,
    },
    {
        id: 'script-js',
        name: 'script.js',
        type: 'file',
        extension: 'js',
        content: `// JavaScript for your project

document.addEventListener('DOMContentLoaded', function() {
    console.log('Project loaded successfully!');
    
    // Add your JavaScript here
});`,
        saved: true,
    },
    {
        id: 'readme-md',
        name: 'README.md',
        type: 'file',
        extension: 'md',
        content: `# My HTML Project

A simple HTML project with TailwindCSS.

## Getting Started

1. Open \`index.html\` in your browser
2. Start editing the files to build your website
3. Add more pages as needed

## Files

- \`index.html\` - Main page
- \`styles.css\` - Custom styles
- \`script.js\` - JavaScript functionality

## Features

- TailwindCSS for styling
- Responsive design ready
- Clean project structure`,
        saved: true,
    },
];
